#ifndef PIONEERS3D_E_TEXTURE_TYPE_HPP
#define PIONEERS3D_E_TEXTURE_TYPE_HPP

namespace pioneers3d {

enum ETextureType
{
	UNKNOWN = 0,
	ROBBER_BG, PLAYER_1_BG, PLAYER_2_BG, PLAYER_3_BG, PLAYER_4_BG,
	TILE_BG, TILE_WASSER, TILE_HOLZ, TILE_LEHM,	TILE_WEIZEN, TILE_WOLLE, TILE_ERZ,
	HAFEN_BG, HAFEN_4zu1, HAFEN_LEHM, HAFEN_HOLZ, HAFEN_WEIZEN, HAFEN_ERZ, HAFEN_WOLLE,
	CARD_BG, CARD_KNIGHT, CARD_VICTORY_POINT, CARD_TRADE_POINT, CARD_INVENTION, CARD_FREE_BANK,
	DICE_BG, DICE_1, DICE_2, DICE_3, DICE_4, DICE_5, DICE_6,
	CHIP_BG, CHIP_2, CHIP_3, CHIP_4, CHIP_5, CHIP_6, CHIP_7, CHIP_8, CHIP_9, CHIP_10, CHIP_11, CHIP_12,
	PLAN_BG, PLAN_STANDARD,
	BANK_BG, BANK_WEIZEN, BANK_WEIZEN,
	COUNT
};

const char* const s_TextureNames[] =
{
	"TEX_WASSER.png",
	"TEX_HOLZ.png",
	"TEX_LEHM.png",
	"TEX_WEIZEN.png",
	"TEX_WOLLE.png",
	"TEX_ERZ.png",
	"TEX_AUGEN_02.png",
	"TEX_AUGEN_03.png",
	"TEX_AUGEN_04.png",
	"TEX_AUGEN_05.png",
	"TEX_AUGEN_06.png",
	"TEX_AUGEN_07.png",
	"TEX_AUGEN_08.png",
	"TEX_AUGEN_09.png",
	"TEX_AUGEN_10.png",
	"TEX_AUGEN_11.png",
	"TEX_AUGEN_12.png"
};

} // end namespace pioneers3d

#endif // PIONEERS3D_DATA_IMAGES_HPP
